# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ssp-info.github.io
title: ТКП
email: ssp.disclosure@gmail.com
author:
description: 'Архив материалов о Тайной Космической Программе. По результатам интервью Дэвида Уилкока с Кори Гудом. Проект «Космическое Раскрытие».'
keywords:    'Кори Гуд, Дэвид Уилкок, Космическое Раскрытие, Голубые Авиане, Альянс Сфер, Хранители Солнца, Межпланетный Корпоративный Конгломерат, МКК, Темный Флот, Глабальная Галактическая Лига Наций, Земной Альянс, Космический Альянс, Управление Лунными Операциями, Внутренняя Земля, Искусственный Интеллект, Раса Древних Строителей'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url:   https://twitter.com/ssp_rus
  - title: email
    url:   mailto:ssp.disclosure@gmail.com

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - tasks.py
    - .editorconfig
