# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: 
title: ТКП
email: ssp.disclosure@gmail.com
author: 
description: 'Тайная Космическая Программа, ТКП, Раскрытие, Хранители Солнца, Межпланетный Корпоративный Конгломерат, МКК, Темный Флот, Глобальная Галактическая Лига Наций, Земной Альянс, Космический Альянс, Голубые Авиане, Альянс Сфер, Кори Гуд.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url:   https://twitter.com/ssp_rus
  - title: email
    url:   mailto:ssp.disclosure@gmail.com
